### ISSUE TITLE
Error Uncompressing Data Using the Lambda Function

### ISSUE THREAD

**Issue by carlbobtx** [awslabs/cloudwatch-logs-centralize-logs#1]
When I implement the Lambda function as is I get this error when it tries to unzip the ELB logs from the S3 bucket - any ideas why?

2016-12-12T23:01:16.036Z	704e2ee6-c0be-11e6-b0e4-8df2422f7d51	Error uncompressing data { [Error: incorrect header check] errno: -3, code: 'Z_DATA_ERROR' }

**Comment by bdelafouchardiere** [comment]
Same for me, since the ELB logs are not compressed when store into S3, the uncompress is throwing this error, any update to solve this ?

**Comment by nnemani** [comment]
Hi, 

Sorry for the inconvenience. This function works on the Application Load Balancer logs which are compressed. But ELB (now Classic) are not compressed. I will work on updating the function accordingly. 
Again, sorry for the inconvenience.

Thanks and Regards

**Comment by bdelafouchardiere** [comment]
Hi,

Thanks for your feedback. Let us know when you have time for releasing correction.

Cordialement,
Best Regards,


[cid:image001.jpg@01D264DC.53B6FE50]

Bruno De La Fouchardiere
Architecte IT
IT Architect
107 boulevard de la mission marchand
92411 COURBEVOIE CEDEX
Mobile : +33650701875

[cid:image002.png@01D264DC.53B6FE50]<http://www.facebook.com/Carglass.France>

[cid:image003.png@01D264DC.53B6FE50]<http://twitter.com/Carglass_France>

[cid:image004.png@01D264DC.53B6FE50]<http://www.linkedin.com/company/carglass_2>

[cid:image005.png@01D264DC.53B6FE50]<http://www.carglass.fr/>

www.carglass.fr


[cid:image006.jpg@01D264DC.53B6FE50]





De : nnemani [mailto:notifications@github.com]
Envoyé : jeudi 29 décembre 2016 20:52
À : awslabs/cloudwatch-logs-centralize-logs <cloudwatch-logs-centralize-logs@noreply.github.com>
Cc : De La Fouchardiere Bruno <bdelafouchardiere@carglass.fr>; Comment <comment@noreply.github.com>
Objet : Re: [awslabs/cloudwatch-logs-centralize-logs] Error Uncompressing Data Using the Lambda Function (#1)


Hi,

Sorry for the inconvenience. This function works on the Application Load Balancer logs which are compressed. But ELB (now Classic) are not compressed. I will work on updating the function accordingly.
Again, sorry for the inconvenience.

Thanks and Regards

**Comment by nikunjnaws** [comment]
Hi,

I have added another lambda function, classic-index.js to support uncompressed logs from classic load balancer type. Updated the README.md (In Instructions) to reflect the same. Please give it a try and let me know if you run into any issues.

Thanks and Regards

**Comment by bdelafouchardiere** [comment]
works like a charm, thanks.

Bruno
