### ISSUE TITLE
Classic ELB Logging

### ISSUE THREAD

**Issue by carlbobtx** [awslabs/cloudwatch-logs-centralize-logs#2]
Hello -

I tried out your classic ELB Lambda function today.  While it does get the log data into a log stream, it's not listing each log entry line by line, it's putting the logs into groups in the stream sorted by the time they get put in.  Each group can contain hundreds of log entries.  This is fairly easy to see in Cloudwatch.  So, for example if I have a log that has 100 requests in 5 minutes, there are not 100 lines in the Log Stream - there may be only 2 lines with 50 entries grouped under each line.  When you try and setup a metric filter pattern to match errors or counts, it will only match if the first line in the group matches the pattern - it ignores the additional lines in the group.  I think each line needs to be listed individually in the log stream for this to work - otherwise you cannot create metric filters that work.  If I'm wrong let me know. I am still learning.

**Comment by nikunjnaws** [comment]
Hello,

Thanks for letting us know. And apologize for the inconvenience. You are right that all the log messages go as one entry and not as individual log events. We will update the code to put each log message as a separate log event. 

Thanks,
Amazon CloudWatch Team

**Comment by nikunjnaws** [comment]
Hello,

The Lambda functions have been updated to send each log entry in the load balancer as an individual log event in CloudWatch Logs. Also the timestamp of each log event is now the timestamp of the actual log message from the load balancer. Your metric filters should now extract a metric for each log event.

Please let us know if you face any other issue.

Thanks,
Amazon CloudWatch Team

**Comment by rajuoo7** [comment]
Hello,
I tried out the ELB function, i am getting "errorMessage": "RequestId: 5984f9b1-064f-11e8-9bd1-391ac2c80383 Process exited before completing request", The type Error i am getting is TypeError: Cannot read property '0' of undefined
    at exports.handler.s3.getObject.rl.on.doNext
Please help me with this

Thanks,
Raju
